name: Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH and known_hosts
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        rsync -avz --delete ./ ubuntu@${{ secrets.EC2_HOST }}:/home/ubuntu/site/
        ssh ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
          sudo rm -rf /var/www/html/*
          sudo cp -r /home/ubuntu/site/* /var/www/html/
        EOF
